vscode:
    extensions:
        - platformio.platformio-ide
tasks:
    - before: pip3 install -U platformio
      init: platformio upgrade --dev && platformio update
      command: platformio run -e wthermostat