language: python
python:
  - '3.7'
sudo: false
install:
  - pip install -U platformio
  - platformio upgrade --dev
  - platformio update
  - git submodule init
  - git submodule update

cache: false

env:
  - ENV=wthermostat

script:
  - platformio run -e $ENV
before_deploy:
  - for file in build_output/firmware/*.bin; do cp $file ${file%/*}.bin; done
